# this what you want to be the default wiki page
startpage: Welcome_to_Junebug
mathml_enable: false

# server configuration
host: 127.0.0.1
port: 3301

# super-secret secret for sessions: change this!
secret: Phyllophaga

# if you want to have the wiki root running on something other than /
sitepath: /

# database configuration
dbconnection:
#
# sqlite3 configuration
  adapter: sqlite3
  database: junebug.db
#
## postgresql configuration
#  adapter: postgresql
#  database: junebug
#  username:
#  password:
#  socket: /tmp
#
## mysql configuration
#  adapter: mysql
#  database: junebug
#  username:
#  password:
#  host: localhost

# configuring rss
feedtitle: Wiki Updates
#
# Optional feed parameters:
#
# Example proxy config:
#feedurl: http://www.mywiki.com/all/feed
#siteurl: http://www.mywiki.com
#
# Example feedburner config:
#feedurl: http://feeds.feedburner.com/MyWiki
#siteurl: http://www.mywiki.com


